config/routes.rb
Rails.application.routes.draw do

  # Routes for groups (we want only to create new groups)
  resources :groups, only: [:create, :new]

  # Routes for visitors (we want all CRUD operations)
  resources :visitors

  # Routes for questions (we want CRUD)
  resources :questions

  # Routes for surveys (we want only to create new surveys)
  resources :surveys, only: [:create, :new]

  # Routes for administrators
  resources :admins, only: [:create, :edit, :update, :new]

  # Home page
  root 'groups#new'

  # Administrator section
  get 'admin' => 'visitors_statistics#show'
  get 'administrator' => 'visitors_statistics#show'

  # Visitor singin page
  get 'signin' => 'groups#new', as: 'sign_in'

  # Visitors statistics page
  get 'visitors_statistics/show', as: 'visitors_statistics'

  # Visitors charts page
  get 'charts' => 'visitors_statistics#charts'

  # Visitors flot charts page
  get 'chartkick_charts' => 'visitors_statistics#chartkick_charts'

  # City autocomplete
  get 'zipcodes/city' => 'zipcodes#city'

  # Filtering area
  get 'filter_area'  => 'visitors#filter_area'

  # Routes for administrator login system
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  # Routes for adding a new administrator
  get 'signup'  => 'admins#new'

  # Visitor singin page
  get 'team' => 'groups#team', as: 'team'

  # Password reset
  resources :password_resets, only: [:create, :edit, :update]

  resource :visitors_statistics do
    post 'visitors_in_date'
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  attr_accessor :remember_token, :activation_token, :reset_token

  #before_save { self.email = email.downcase }

  # validates user name for presence and length
  validates :user_name, presence: true, length: {maximum: 50}

  #VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  #validates :email, presence: true, length: {maximum: 255},
  #          format: {with: VALID_EMAIL_REGEX},
  #          uniqueness: {case_sensitive: false}

  # handles password
  has_secure_password
  validates :password, length: {minimum: 6}

  # Returns the hash digest of the given string.
  def Admin.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def Admin.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a admin in the database for use in persistent sessions.
  def remember
    self.remember_token = Admin.new_token
    update_attribute(:remember_digest, Admin.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated_remember?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # Forgets a admin.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = Admin.new_token
    update_attribute(:reset_digest,  Admin.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    AdminMailer.password_reset(self).deliver_now
  end

  # Returns true if a password reset has expired.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  self.table_name = 'answers'
  # has_many :visitors
  belongs_to :question
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :visitors
end

app/models/filtered_zipcode.rb
class FilteredZipcode < ActiveRecord::Base
  self.table_name = 'filtered_zipcodes'
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :visitors
  accepts_nested_attributes_for :visitors

  has_many :surveys
  has_many :questions, through: :surveys
  accepts_nested_attributes_for :surveys
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :surveys
  has_many :groups, through: :surveys

  has_many :answers
  accepts_nested_attributes_for :answers
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :group
  belongs_to :question
end

app/models/texas_zipcode.rb
class TexasZipcode < ActiveRecord::Base
  self.table_name = 'texas_zipcodes'
  has_many :visitors
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
  belongs_to :group
  belongs_to :zipcode
  belongs_to :country

  def self.to_csv(options = {}, start_date = '', end_date = '')
  CSV.generate(options) do |csv|
    csv << ["First Name", "Last Name"]
    all.each do |visitor|
      csv << [visitor.first_name, visitor.last_name]
    end
  end
  end
end

app/models/zipcode.rb
class Zipcode < ActiveRecord::Base
	self.primary_key = 'zip_code'
	has_many :visitors
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
require 'bcrypt'

module SessionsHelper
  # Logs in the given admin.
  def log_in(admin)
    session[:admin_id] = admin.id
  end

  # Remembers a admin in a persistent session.
  def remember(admin)
    admin.remember
    cookies.permanent.signed[:admin_id] = admin.id
    cookies.permanent[:remember_token] = admin.remember_token
  end

  # Returns the admin corresponding to the remember token cookie.
  def current_admin
    if (admin_id = session[:admin_id])
      @current_admin ||= Admin.find_by(id: admin_id)
    elsif (admin_id = cookies.signed[:admin_id])
      admin = Admin.find_by(id: admin_id)
      if admin && admin.authenticated_remember?(cookies[:remember_token])
        log_in admin
        @current_admin = admin
      end
    end
  end

  # Returns true if the admin is logged in, false otherwise.
  def logged_in?
    !current_admin.nil?
  end
  # Returns the hash digest of the given string.
  def Admin.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Forgets a persistent session. def forget(admin)
  def forget(admin)
    admin.forget
    cookies.delete(:admin_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_admin)
    session.delete(:admin_id)
    @current_admin = nil
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/helpers/zipcodes_helper.rb
module ZipcodesHelper
end

app/views/admins/edit.html.erb
<div class="content">
  <!--<div class="page-header">-->
    <!--<h1>Settings</h1>-->
  <!--</div>-->
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">Settings</h1>
    </div>
  </div>

  <div class="row">
    <h2 class="page-header" style="text-align: center">Change Password</h2>
    <div class="col-md-6 col-md-offset-3">
      <%= render 'form' %>
    </div>
  </div>

<%# <%= link_to 'Show', @admin %>
<%# <%= link_to 'Back', admins_path %>
</div>

app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admins</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.user_name %></td>
        <td><%= admin.password_digest %></td>
        <td><%= link_to 'Show', admin %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_path %>

app/views/admins/new.html.erb
<div class="content">
  <div class="page-header">
    <% provide(:title, 'Sign up') %>
    <h1>Add Administrator</h1>
  </div>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@admin) do |f| %>
          <%= render 'shared/error_messages' %>
          <div class="field">
            <%#<%= f.label :user_name %>
            <%= f.text_field :user_name, class: 'form-control', placeholder: :user_name %>
          </div>

          <%# <%= f.label :email %>
          <%#<%= f.email_field :email %>

          <div class="field">
            <%#<%= f.label :password %>
            <%= f.password_field :password, class: 'form-control', placeholder: :password %>
          </div>

          <div class="field">
            <%#<%= f.label :password_confirmation, "Verify password" %>
            <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Verify password" %>
          </div>

          <div class="actions">
            <%= f.submit "Add administrator", class: "btn btn-primary" %>
          </div>
      <% end %>
    </div>
  </div>

  <%#<%= link_to 'Back', admins_path %>
</div>

app/views/admins/show.html.erb
<div class="content">
  <div class="page-header">
     <h1>My Profile</h1>
  </div>
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @admin.user_name %>
</p>

<p>
  <strong>Password Digest:</strong>
  <%= @admin.password_digest %>
</p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>

</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>M.O.S.S Administration Page</title>

  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->

</head>

<body>

<div id="wrapper">

  <!-- Navigation -->
  <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0;">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--<a class="navbar-brand" href="index.html">MOSS ADMINISTRATION</a>-->
      <%= link_to 'M.O.S.S ADMINISTRATION', visitors_statistics_path, :class => 'navbar-brand'%>
    </div>
    <!-- /.navbar-header -->

    <ul class="nav navbar-top-links navbar-right">
      <!--<li class="dropdown">-->
        <!--<a class="dropdown-toggle" data-toggle="dropdown" href="#">-->
          <!--<i class="fa fa-envelope fa-fw"></i>  <i class="fa fa-caret-down"></i>-->
        <!--</a>-->
        <!--<ul class="dropdown-menu dropdown-messages">-->
          <!--<li>-->
            <!--<a href="#">-->
              <!--<div>-->
                <!--<strong>John Smith</strong>-->
                                    <!--<span class="pull-right text-muted">-->
                                        <!--<em>Yesterday</em>-->
                                    <!--</span>-->
              <!--</div>-->
              <!--<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>-->
            <!--</a>-->
          <!--</li>-->
          <!--<li class="divider"></li>-->
          <!--<li>-->
            <!--<a href="#">-->
              <!--<div>-->
                <!--<strong>John Smith</strong>-->
                                    <!--<span class="pull-right text-muted">-->
                                        <!--<em>Yesterday</em>-->
                                    <!--</span>-->
              <!--</div>-->
              <!--<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>-->
            <!--</a>-->
          <!--</li>-->
          <!--<li class="divider"></li>-->
          <!--<li>-->
            <!--<a href="#">-->
              <!--<div>-->
                <!--<strong>John Smith</strong>-->
                                    <!--<span class="pull-right text-muted">-->
                                        <!--<em>Yesterday</em>-->
                                    <!--</span>-->
              <!--</div>-->
              <!--<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>-->
            <!--</a>-->
          <!--</li>-->
          <!--<li class="divider"></li>-->
          <!--<li>-->
            <!--<a class="text-center" href="#">-->
              <!--<strong>Read All Messages</strong>-->
              <!--<i class="fa fa-angle-right"></i>-->
            <!--</a>-->
          <!--</li>-->
        <!--</ul>-->
        <!-- /.dropdown-messages -->
      <!--</li>-->
      <!-- /.dropdown -->
      <!--<li class="dropdown">-->
        <!--<a class="dropdown-toggle" data-toggle="dropdown" href="#">-->
          <!--<i class="fa fa-tasks fa-fw"></i>  <i class="fa fa-caret-down"></i>-->
        <!--</a>-->
        <!--<ul class="dropdown-menu dropdown-tasks">-->
          <!--<li>-->
            <!--<a href="#">-->
              <!--<div>-->
                <!--<p>-->
                  <!--<strong>Task 1</strong>-->
                  <!--<span class="pull-right text-muted">40% Complete</span>-->
                <!--</p>-->
                <!--<div class="progress progress-striped active">-->
                  <!--<div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">-->
                    <!--<span class="sr-only">40% Complete (success)</span>-->
                  <!--</div>-->
                <!--</div>-->
              <!--</div>-->
            <!--</a>-->
          <!--</li>-->
          <!--<li class="divider"></li>-->
          <!--<li>-->
            <!--<a href="#">-->
              <!--<div>-->
                <!--<p>-->
                  <!--<strong>Task 2</strong>-->
                  <!--<span class="pull-right text-muted">20% Complete</span>-->
                <!--</p>-->
                <!--<div class="progress progress-striped active">-->
                  <!--<div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">-->
                    <!--<span class="sr-only">20% Complete</span>-->
                  <!--</div>-->
                <!--</div>-->
              <!--</div>-->
            <!--</a>-->
          <!--</li>-->
          <!--<li class="divider"></li>-->
          <!--<li>-->
            <!--<a href="#">-->
              <!--<div>-->
                <!--<p>-->
                  <!--<strong>Task 3</strong>-->
                  <!--<span class="pull-right text-muted">60% Complete</span>-->
                <!--</p>-->
                <!--<div class="progress progress-striped active">-->
                  <!--<div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">-->
                    <!--<span class="sr-only">60% Complete (warning)</span>-->
                  <!--</div>-->
                <!--</div>-->
              <!--</div>-->
            <!--</a>-->
          <!--</li>-->
          <!--<li class="divider"></li>-->
          <!--<li>-->
            <!--<a href="#">-->
              <!--<div>-->
                <!--<p>-->
                  <!--<strong>Task 4</strong>-->
                  <!--<span class="pull-right text-muted">80% Complete</span>-->
                <!--</p>-->
                <!--<div class="progress progress-striped active">-->
                  <!--<div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">-->
                    <!--<span class="sr-only">80% Complete (danger)</span>-->
                  <!--</div>-->
                <!--</div>-->
              <!--</div>-->
            <!--</a>-->
          <!--</li>-->
          <!--<li class="divider"></li>-->
          <!--<li>-->
            <!--<a class="text-center" href="#">-->
              <!--<strong>See All Tasks</strong>-->
              <!--<i class="fa fa-angle-right"></i>-->
            <!--</a>-->
          <!--</li>-->
        <!--</ul>-->
        <!--&lt;!&ndash; /.dropdown-tasks &ndash;&gt;-->
      <!--</li>-->
      <!-- /.dropdown -->
      <!--<li class="dropdown">-->
        <!--<a class="dropdown-toggle" data-toggle="dropdown" href="#">-->
          <!--<i class="fa fa-bell fa-fw"></i>  <i class="fa fa-caret-down"></i>-->
        <!--</a>-->
        <!--<ul class="dropdown-menu dropdown-alerts">-->
          <!--<li>-->
            <!--<a href="#">-->
              <!--<div>-->
                <!--<i class="fa fa-comment fa-fw"></i> New Comment-->
                <!--<span class="pull-right text-muted small">4 minutes ago</span>-->
              <!--</div>-->
            <!--</a>-->
          <!--</li>-->
          <!--<li class="divider"></li>-->
          <!--<li>-->
            <!--<a href="#">-->
              <!--<div>-->
                <!--<i class="fa fa-twitter fa-fw"></i> 3 New Followers-->
                <!--<span class="pull-right text-muted small">12 minutes ago</span>-->
              <!--</div>-->
            <!--</a>-->
          <!--</li>-->
          <!--<li class="divider"></li>-->
          <!--<li>-->
            <!--<a href="#">-->
              <!--<div>-->
                <!--<i class="fa fa-envelope fa-fw"></i> Message Sent-->
                <!--<span class="pull-right text-muted small">4 minutes ago</span>-->
              <!--</div>-->
            <!--</a>-->
          <!--</li>-->
          <!--<li class="divider"></li>-->
          <!--<li>-->
            <!--<a href="#">-->
              <!--<div>-->
                <!--<i class="fa fa-tasks fa-fw"></i> New Task-->
                <!--<span class="pull-right text-muted small">4 minutes ago</span>-->
              <!--</div>-->
            <!--</a>-->
          <!--</li>-->
          <!--<li class="divider"></li>-->
          <!--<li>-->
            <!--<a href="#">-->
              <!--<div>-->
                <!--<i class="fa fa-upload fa-fw"></i> Server Rebooted-->
                <!--<span class="pull-right text-muted small">4 minutes ago</span>-->
              <!--</div>-->
            <!--</a>-->
          <!--</li>-->
          <!--<li class="divider"></li>-->
          <!--<li>-->
            <!--<a class="text-center" href="#">-->
              <!--<strong>See All Alerts</strong>-->
              <!--<i class="fa fa-angle-right"></i>-->
            <!--</a>-->
          <!--</li>-->
        <!--</ul>-->
        <!--&lt;!&ndash; /.dropdown-alerts &ndash;&gt;-->
      <!--</li>-->
      <!-- /.dropdown -->
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-user">
          <%# <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>%>
          <%# </li>%>
          <li>
            <%= link_to raw('<i class="fa fa-gear fa-fw"></i> Settings'), edit_admin_path(current_admin), id: "settings" %>
          </li>
          <%# <li class="divider"></li>%>
          <li>
            <%= link_to raw('<i class="fa fa-sign-out fa-fw"></i> Logout'), logout_path, method: "delete", id: "logout" %>
          </li>
        </ul>
        <!-- /.dropdown-user -->
      </li>
      <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->

    <div class="navbar-default sidebar" role="navigation">
      <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
          <!--<li class="sidebar-search">-->
            <!--<div class="input-group custom-search-form">-->
              <!--<input type="text" class="form-control" placeholder="Search...">-->
                                <!--<span class="input-group-btn">-->
                                <!--<button class="btn btn-default" type="button">-->
                                  <!--<i class="fa fa-search"></i>-->
                                <!--</button>-->
                            <!--</span>-->
            <!--</div>-->
            <!--&lt;!&ndash; /input-group &ndash;&gt;-->
          <!--</li>-->
          <li>
            <%= link_to visitors_statistics_path do %>
                <i class="fa fa-dashboard fa-fw"></i> Dashboard
            <% end %>
          </li>
          <li>
            <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Charts<span class="fa arrow"></span></a>
            <ul class="nav nav-second-level">
              <li>
                <!--<a href="#">Flot Charts</a>-->
                <%= link_to 'Chartkick Charts', chartkick_charts_path %>
              </li>
              <li>
                <%= link_to 'Morris Charts', charts_path %>
              </li>
            </ul>
            <!-- /.nav-second-level -->
          </li>
          <li>
            <%= link_to visitors_path do %>
                <i class="fa fa-table fa-fw"></i> Visitors Table
            <% end %>
          </li>
          <li>
            <%= link_to questions_path do %>
                <i class="fa fa-edit fa-fw"></i> Survey Questions
            <% end %>
          </li>
        </ul>
      </div>
      <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
  </nav>

  <div id="page-wrapper" style="min-height: 386px;">
    <%= yield %>
  </div>
  <!-- /#page-wrapper -->

</div>

</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>M.O.S.S</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>

</head>

<body id="page-top" class="index">

<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top" style="border-color: transparent; background-color: #222;">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header page-scroll">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--<a class="navbar-brand scroll" href="#page-top" style="font-family: 'Kaushan Script','Helvetica Neue',Helvetica,Arial,cursive; color: #fed136;">Museum of American G.I.</a>-->
      <a class="navbar-brand scroll" href="#page-top" style="font-family: 'Stencil'; font-size: 20px; color: #fed136;">Museum of American G.I.</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="hidden">
          <a href="#page-top"></a>
        </li>
        <li>
          <a class="scroll" href="#zip-code" style="font-family: 'Helvetica'; font-size: 15px; color: #fed136">Zip Code</a>
        </li>
        <li>
          <a class="scroll" href="#information" style="font-family: 'Helvetica'; font-size: 15px; color: #fed136">Visitor Information</a>
        </li>
        <li>
          <a class="scroll" href="#survey" style="font-family: 'Helvetica'; font-size: 15px; color: #fed136">Survey</a>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>


  <!--<!% flash.each do |message_type, message| %>-->
    <!--<div id="alert">-->
      <!--<div class="alert alert-<!%= message_type %>">-->
        <!--<!%= message %>-->
      <!--</div>-->
    <!--</div>-->
  <!--<!% end %>-->

<div>
  <%= yield %>
</div>

<footer>
  <div class="container">
    <div class="row">
      <!--<div class="col-md-4">-->
        <span class="copyright" style="color: #fed136">Copyright &copy; <%= link_to "The Dining Philosophers", team_path, :style => "color: #fed136" %> <%= (Date.today).strftime("%Y") %></span>
      <!--</div>-->
      <!--<div class="col-md-4">-->
        <!--<ul class="list-inline social-buttons">-->
        <!--<li><a href="#"><i class="fa fa-twitter"></i></a>-->
        <!--</li>-->
        <!--<li><a href="#"><i class="fa fa-facebook"></i></a>-->
        <!--</li>-->
        <!--<li><a href="#"><i class="fa fa-linkedin"></i></a>-->
        <!--</li>-->
        <!--</ul>-->
      <!--</div>-->
      <!--<div class="col-md-4">-->
        <!--<ul class="list-inline quicklinks">-->
          <!--&lt;!&ndash;<li><a href="#">Privacy Policy</a>&ndash;&gt;-->
          <!--&lt;!&ndash;</li>&ndash;&gt;-->
          <!--&lt;!&ndash;<li><a href="#">Terms of Use</a>&ndash;&gt;-->
          <!--&lt;!&ndash;</li>&ndash;&gt;-->
          <!--<li><a href="visitors_statistics" style="color: #fed136; font-size: 15px">Administration</a></li>-->
        <!--</ul>-->
      <!--</div>-->
    </div>
  </div>
</footer>

<!--{cms_jquery}-->

<script type="text/javascript">
  jQuery(document).ready(function($) {
    $(".scroll").click(function(event) {
    event.preventDefault();
    $('html,body').animate( { scrollTop:$(this.hash).offset().top } , 500);
    } );
  } );
</script>

</body>
</html>