config/routes.rb
Rails.application.routes.draw do

  # Routes for groups (we want only to create new groups)
  resources :groups, only: [:create, :new]

  # Routes for visitors (we want all CRUD operations)
  resources :visitors

  # Routes for questions (we want CRUD)
  resources :questions

  # Routes for surveys (we want only to create new surveys)
  resources :surveys, only: [:create, :new]

  # Routes for administrators
  resources :admins, only: [:create, :edit, :update, :new]

  # Home page
  root 'groups#new'

  # Administrator section
  get 'admin' => 'visitors_statistics#show'
  get 'administrator' => 'visitors_statistics#show'

  # Visitor singin page
  get 'signin' => 'groups#new', as: 'sign_in'

  # Visitors statistics page
  get 'visitors_statistics/show', as: 'visitors_statistics'

  # Visitors charts page
  get 'charts' => 'visitors_statistics#charts'

  # Visitors flot charts page
  get 'chartkick_charts' => 'visitors_statistics#chartkick_charts'

  # City autocomplete
  get 'zipcodes/city' => 'zipcodes#city'

  # Filtering area
  get 'filter_area'  => 'visitors#filter_area'

  # Routes for administrator login system
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  # Routes for adding a new administrator
  get 'signup'  => 'admins#new'

  # Visitor singin page
  get 'team' => 'groups#team', as: 'team'

  # Password reset
  resources :password_resets, only: [:create, :edit, :update]

  resource :visitors_statistics do
    post 'visitors_in_date'
  end
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
  belongs_to :group
  belongs_to :zipcode
  belongs_to :country

  def self.to_csv(options = {}, start_date = '', end_date = '')
  CSV.generate(options) do |csv|
    csv << ["First Name", "Last Name"]
    all.each do |visitor|
      csv << [visitor.first_name, visitor.last_name]
    end
  end
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  require 'csv'
  before_action :set_visitor, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user

  def index
    @start_date = params[:start_date]
    @end_date = params[:end_date]
    @contactable = params[:contactable]

    if(@start_date.blank? || @end_date.blank?)
      @end_date = DateTime.now.at_end_of_day
      @start_date = (DateTime.now - 365.days)
      @start_date = @start_date.at_end_of_day
    else
      @start_date = DateTime.strptime(@start_date,'%m/%d/%Y').at_beginning_of_day
      @end_date = DateTime.strptime(@end_date,'%m/%d/%Y').at_end_of_day
    end
    if(@contactable == "1")
      @visitors = Visitor.where(:created_at => @start_date..@end_date).where(:contact => true)
    else
      @visitors = Visitor.where(:created_at => @start_date..@end_date)
    end

    render :layout => 'admin'

  end

  def filter_area
    @start_date=params[:start_date]
    @start_date = DateTime.strptime(@start_date,'%m/%d/%Y').at_beginning_of_day
    @end_date=params[:end_date]
    @end_date = DateTime.strptime(@end_date,'%m/%d/%Y').at_end_of_day

    @area=params[:area]
    @contactable=params[:contactable]

    # begin of "This part is not optimized and can be improved"

    if(@area.size == 7 || @area.size == 0)
      # @visitors = Visitor.where(:created_at => @start_date..@end_date)
      if(@contactable == '1')
        @visitors = Visitor.where(:created_at => @start_date..@end_date).where(:contact => true)
      else
        @visitors = Visitor.where(:created_at => @start_date..@end_date)
      end
    else
      @visitors = []
      if(@area.include?('Austin'))
        @visitors += Visitor.where(:created_at => @start_date..@end_date).
            where(:zip_code => FilteredZipcode.where(:area => 'Austin').
                uniq.pluck(:zip_code))
      end
      if(@area.include?('Houston'))
        @visitors += Visitor.where(:created_at => @start_date..@end_date).
            where(:zip_code => FilteredZipcode.where(:area => 'Houston').
                uniq.pluck(:zip_code))
      end
      if(@area.include?('San Antonio'))
        @visitors += Visitor.where(:created_at => @start_date..@end_date).
            where(:zip_code => FilteredZipcode.where(:area => 'San Antonio').
                uniq.pluck(:zip_code))
      end
      if(@area.include?('bcs'))
        @visitors += Visitor.where(:created_at => @start_date..@end_date).
            where(:zip_code => FilteredZipcode.where(:area => 'College Station').
            uniq.pluck(:zip_code))
      end
      if(@area.include?('df'))
        @visitors += Visitor.where(:created_at => @start_date..@end_date).
            where(:zip_code => FilteredZipcode.where(:area => 'Dallas/Fort Worth').
                uniq.pluck(:zip_code))
      end
      if(@area.include?('ocit'))
        # @visitors += Visitor.where(:created_at => @start_date..@end_date).
        #     where(:zip_code => TexasZipcode.uniq.pluck(:zip_code)).
        #     where.not(:zip_code => FilteredZipcode.uniq.pluck(:zip_code))
        @visitors += Visitor.where(:created_at => @start_date..@end_date).
            where(:zip_code => Zipcode.where(:state => 'TX').uniq.pluck(:zip_code)).
            where.not(:zip_code => FilteredZipcode.uniq.pluck(:zip_code))
      end
      if(@area.include?('oos'))
        # @visitors += Visitor.where(:created_at => @start_date..@end_date).
        #     where.not(:zip_code => (TexasZipcode.uniq.pluck(:zip_code) << '00000'))
        @visitors += Visitor.where(:created_at => @start_date..@end_date).
            where.not(:zip_code => (Zipcode.where(:state => 'TX').uniq.pluck(:zip_code) << '00000'))
      end
      if(@area.include?('N/A'))
        @visitors += Visitor.where(:created_at => @start_date..@end_date).
            where(:zip_code => ['00000'])
      end

      if(@contactable == '1')
        @visitors = @visitors.select{|visitor| visitor.contact == true}
      end

    end

    render :partial => 'visitors/filter_area', :content_type => 'text/html'


  end

  # def filter_area
  #   @df = Array.new
  #   @df <<'Addison'<<'Allen'<<'Carrollton'<<'Celina'<<'Coppell'<<'Flower Mound'<<'Plano'<<
  #       'Rockwall'<<'Frisco'<<'Irving'<<'Garland'<<'Sachse'<<'Grand Prairie'<<'The Colony'<<
  #       'Lewisville'<<'Lake Dallas'<<'Little Elm'<<'Mckinney'<<'Prosper'<<'Richardson'<<'Rowlett'<<
  #       'Wylie'<<'Bardwell'<<'Cedar Hill'<<'Crandall'<<'Desoto'<<'Duncanville'<<'Ennis'<<'Ferris'<<
  #       'Forney'<<'Fate'<<'Lancaster'<<'Caddo Mills'<<'Hutchins'<<'Kaufman'<<'Mabank'<<'Mesquite'<<
  #       'Palmer'<<'Red Oak'<<'Rosser'<<'Scurry'<<'Seagoville'<<'Terrell'<<'Josephine'<<'Waxahachie'<<
  #       'Lavon'<<'Wilmer'<<'Nevada'<<'Sunnyvale'<<'Royse City'<<'Dallas'<<'Greenville'<<'Princeton'<<
  #       'Anna'<<'Ben Franklin'<<'Campbell'<<'Celeste'<<'Blue Ridge'<<'Commerce'<<'Cooper'<<'Enloe'<<
  #       'Farmersville'<<'Klondike'<<'Lake Creek'<<'Lone Oak'<<'Melissa'<<'Pecan Gap'<<'Quinlan'<<
  #       'Wolfe City'<<'Arlington'<<'Aledo'<<'Alvarado'<<'Azle'<<'Bedford'<<'Boyd'<<'Burleson'<<
  #       'Cleburne'<<'Colleyville'<<'Crowley'<<'Euless'<<'Forreston'<<'Godley'<<'Grandview'<<
  #       'Grapevine'<<'Haslet'<<'Hurst'<<'Joshua'<<'Keene'<<'Kennedale'<<'Lillian'<<'Mansfield'<<
  #       'Maypearl'<<'Midlothian'<<'Millsap'<<'Newark'<<'Paradise'<<'Rhome'<<'Springtown'<<'Venus'<<
  #       'Weatherford'<<'Southlake'<<'Rio Vista'<<'Fort Worth'<<'Haltom City'<<'Naval Air Station/ Jrb'<<
  #       'North Richland Hills'<<'Denton'<<'Alvord'<<'Argyle'<<'Aubrey'<<'Decatur'<<'Keller'<<'Justin'<<
  #       'Krum'<<'Pilot Point'<<'Ponder'<<'Roanoke'<<'Sanger'<<'Bridgeport'<<'Chico'<<'Poolville'<<
  #       'Whitt'<<'Avalon'<<'Italy'<<'Milford'
  #
  #   @start_date=params[:start_date]
  #   @start_date = DateTime.strptime(@start_date,'%m/%d/%Y').at_beginning_of_day
  #   @end_date=params[:end_date]
  #   @end_date = DateTime.strptime(@end_date,'%m/%d/%Y').at_end_of_day
  #
  #   @area=params[:area]
  #   @contactable=params[:contactable]
  #
  #   # begin of "This part is not optimized and can be improved"
  #
  #   if(@area.size == 7 || @area.size == 0)
  #     # @visitors = Visitor.where(:created_at => @start_date..@end_date)
  #     if(@contactable == "1")
  #       @visitors = Visitor.where(:created_at => @start_date..@end_date).where(:contact => true)
  #     else
  #       @visitors = Visitor.where(:created_at => @start_date..@end_date)
  #     end
  #   else
  #     if(@area.include?('bcs'))
  #       @area << 'College Station' << 'Bryan'
  #     end
  #     if(@area.include?('df'))
  #       # @area.delete('df')
  #       @area = @area - ['df']
  #       @area << @df
  #     end
  #     if(@area.include?('ocit'))
  #       # @area.delete('ocit')
  #       @area = @area - ['ocit']
  #       @temp = @df
  #       @temp << 'Austin' << 'College Station' << 'San Antonio' << 'Bryan' << 'Houston'
  #       @other = TexasZipcode.uniq.pluck(:city)
  #       @other = @other - @temp
  #       @area << @other
  #     end
  #     if(@area.include?('oos'))
  #       @osc = Zipcode.uniq.pluck(:city)
  #       @other = TexasZipcode.uniq.pluck(:city)
  #       @other << 'N/A'
  #       @area << (@osc - @other)
  #     end
  #     @zipcodes = Zipcode.where(:city => @area)
  #     # @visitors = Visitor.where(:created_at => @start_date..@end_date).where(:zip_code => @zipcodes)
  #     if(@contactable == "1")
  #       @visitors = Visitor.where(:created_at => @start_date..@end_date).where(:contact => true).where(:zip_code => @zipcodes)
  #     else
  #       @visitors = Visitor.where(:created_at => @start_date..@end_date).where(:zip_code => @zipcodes)
  #     end
  #
  #     # end of "This part is not optimized and can be improved"
  #   end
  #
  #   render :partial => 'visitors/filter_area', :content_type => 'text/html'
  #
  #
  # end



  # GET /visitors/1
  # GET /visitors/1.json
  def show
    @n_questions = Question.all #number of questions in the database

    render :partial => 'visitors/show', :content_type => 'text/html'
  end

  # GET /visitors/new
  def new
    @visitor = Visitor.new
  end

  # GET /visitors/1/edit
  def edit
    render :layout => 'admin'
  end

  # POST /visitors
  # POST /visitors.json
  def create
    @visitor = Visitor.new(visitor_params)

    respond_to do |format|
      if @visitor.save
        format.html { redirect_to @visitor, notice: 'Visitor was successfully created.' }
        format.json { render :show, status: :created, location: @visitor }
      else
        format.html { render :new }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visitors/1
  # PATCH/PUT /visitors/1.json
  def update
    respond_to do |format|
      if @visitor.update(visitor_params)
        format.html { redirect_to @visitor, notice: 'Visitor was successfully updated.' }
        format.json { render :show, status: :ok, location: @visitor }
      else
        format.html { render :edit }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visitors/1
  # DELETE /visitors/1.json
  def destroy
    @visitor.destroy
    respond_to do |format|
      format.html { redirect_to visitors_url, notice: 'Visitor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_visitor
    @visitor = Visitor.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def visitor_params
    params.require(:visitor).permit(:last_name, :first_name, :group_id, :email, :contact, :zip_code, :country_id)
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/visitors/_filter_area.html.erb
<div id="div_table" style="margin: 0 auto; text-align:center; padding-bottom: 30px">
  <!--<table class="table table-bordered table-hover sortable results">-->
  <!-- /.row -->
  <div class="row">
    <div class="col-lg-12">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3>Visitors Tables</h3>
        </div>
        <!-- /.panel-heading -->
        <div class="panel-body">
          <div class="dataTable_wrapper">
            <table id="visitors_table" class="table table-striped table-bordered table-hover">
              <thead>
              <tr>
                <th class="table_header">Last name</th>
                <th class="table_header">First name</th>
                <th class="table_header">Visit Date</th>
                <th class="table_header">Email</th>
                <th class="table_header">Contactable</th>
                <th class="table_header">City</th>
                <th class="table_header">Zip code</th>
                <th class="table_header">State</th>
                <th class="table_header">Country</th>
                <th class="table_header"></th>
                <th class="table_header"></th>
                <th class="table_header"></th>
              </tr>
              </thead>


              <tbody>
              <% @visitors.each do |visitor| %>
                  <tr>
                    <td><%= visitor.last_name %></td>
                    <td><%= visitor.first_name %></td>
                    <!--<td><%= visitor.group_id %></td>-->
                    <td><%= visitor.created_at %></td>
                    <td style="word-wrap: break-word"><%= visitor.email %></td>
                    <!--<td style="text-align: center"><%= visitor.contact == true ? content_tag(:span, '',:class => 'glyphicon glyphicon-thumbs-up') : '' %></td>-->
                    <td style="text-align: center"><%= visitor.contact == true ? 'Yes' : 'No' %></td>
                    <td><%= Zipcode.find(visitor.zip_code).city %></td>
                    <td style="text-align: center"><%= visitor.zip_code == '00000'? 'N/A' : visitor.zip_code %></td>
                    <td><%= Zipcode.find(visitor.zip_code).state %></td>
                    <td style="word-wrap: break-word"><%= visitor.country.name %></td>
                    <td style="text-align: center"><button value='<%= visitor.id %>' type="button" class="btn btn-primary btn-xs show_btn" data-toggle="modal" data-target="#myModal"><i class="fa fa-eye fa-1"></i></button></td>
                    <td style="text-align: center"><%= link_to '<i class="fa fa-pencil fa-1"></i>'.html_safe, edit_visitor_path(visitor), class: 'btn btn-warning btn-xs' %></td>
                    <td style="text-align: center"><%= link_to '<i class="fa fa-trash-o fa-1"></i>'.html_safe, visitor, class: 'btn btn-danger btn-xs', method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
          <!-- /.table-responsive -->
        </div>
        <!-- /.panel-body -->
      </div>
      <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
  </div>
  <!-- /.row -->

</div>
<!--</div>-->

<script>
    $( document ).ready(function() {
        if ( $.fn.dataTable.isDataTable( '#visitors_table' ) ) {
          table = $('#visitors_table').DataTable({
            destroy: true,
            "dom": 'T<"clear">lfrtip',
            "tableTools": {
              "sSwfPath": "http://cdn.datatables.net/tabletools/2.2.4/swf/copy_csv_xls_pdf.swf",
              aButtons: [
                {
                  "sExtends": "copy",
                  "sButtonText": "Copy",
                  "mColumns": [ 0, 1, 2, 3, 4, 5, 6, 7, 8 ]
                },
                {
                  "sExtends": "csv",
                  "sButtonText": "CSV",
                  "mColumns": [ 0, 1, 2, 3, 4, 5, 6, 7, 8 ]
                },
                {
                  "sExtends": "pdf",
                  "sButtonText": "PDF",
                  "mColumns": [ 0, 1, 2, 3, 4, 5, 6, 7, 8 ]
                },
                {
                  "sExtends": "xls",
                  "sButtonText": "Excel",
                  "mColumns": [ 0, 1, 2, 3, 4, 5, 6, 7, 8 ]
                },
                {
                  "sExtends": "print",
                  "sButtonText": "Print",
                  "mColumns": [ 0, 1, 2, 3, 4, 5, 6, 7, 8 ]
                },
              ]
            },
            "columnDefs": [ { "targets": 9, "orderable": false },
              { "targets": 10, "orderable": false },
              { "targets": 11, "orderable": false }]
          });
        }
        else {
          table = $('#visitors_table').DataTable({
            destroy: true,
            "dom": 'T<"clear">lfrtip',
            "tableTools": {
              "sSwfPath": "http://cdn.datatables.net/tabletools/2.2.4/swf/copy_csv_xls_pdf.swf",
              aButtons: [
                {
                  "sExtends": "copy",
                  "sButtonText": "Copy",
                  "mColumns": [ 0, 1, 2, 3, 4, 5, 6, 7, 8 ]
                },
                {
                  "sExtends": "csv",
                  "sButtonText": "CSV",
                  "mColumns": [ 0, 1, 2, 3, 4, 5, 6, 7, 8 ]
                },
                {
                  "sExtends": "pdf",
                  "sButtonText": "PDF",
                  "mColumns": [ 0, 1, 2, 3, 4, 5, 6, 7, 8 ]
                },
                {
                  "sExtends": "xls",
                  "sButtonText": "Excel",
                  "mColumns": [ 0, 1, 2, 3, 4, 5, 6, 7, 8 ]
                },
                {
                  "sExtends": "print",
                  "sButtonText": "Print",
                  "mColumns": [ 0, 1, 2, 3, 4, 5, 6, 7, 8 ]
                },
              ]
            },
            "columnDefs": [ { "targets": 9, "orderable": false },
              { "targets": 10, "orderable": false },
              { "targets": 11, "orderable": false }]
          });
        }

        $('.show_btn').click(function () {
            var val = $(this).attr("value")
            $.ajax({
                type: "GET",
                dataType: "html",
                url: "/visitors/" + val.toString(),
                success: function (data) {
                    $('#modal-body').empty();
                    $('#modal-body').append(data);
                }
            });
        });
    });
</script>

app/views/visitors/_form.html.erb
<!--<div class="content">-->
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading" style="text-align: center">
        Visitor
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-lg-6">
            <!--<form role="form">-->
  <%= form_for @visitor, :html=> {:id => 'form1'} do |f| %>
      <% if @visitor.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@visitor.errors.count, "error") %> prohibited this visitor from being saved:</h2>

            <ul>
              <% @visitor.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <div class="field">
        <%= f.label :last_name %><br>
        <%= f.text_field :last_name, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.label :first_name %><br>
        <%= f.text_field :first_name, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.label :group_id %><br>
        <%= f.number_field :group_id, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.label :email %><br>
        <%= f.text_field :email, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.label :contact %><br>
        <%= f.check_box :contact %>
      </div>
      <div class="field">
        <%= f.label :zip_code %><br>
        <%= f.text_field :zip_code, class: "form-control" %>
      </div>
      <div class="field">
        <%= f.label :country_id %><br>
        <%= f.collection_select :country_id, Country.all, :id, :name, {:selected => '215'}, class: "form-control" %>
      </div>
      <div class="actions">
        <%= f.submit %>
      </div>
  <% end %>

  <!--<!%= link_to "Submit", "#", :class => 'button_submit btn btn-danger' %>-->

          </div>
        </div>
      </div>
    </div>
  </div>
</div>
  </br>


  <script type="text/javascript">

  </script>

app/views/visitors/_show.html.erb
<p id="notice"><%= notice %></p>

<div class="modal-header">
  <h2>
    <%= @visitor.first_name + " " + @visitor.last_name %>
  </h2>
</div> 
<!--
<p>
  <strong>Last name:</strong>
  <!= @visitor.last_name %>
</p>

<p>
  <strong>First name:</strong>
  <!= @visitor.first_name %>
</p> 
-->
<p></p>
<p>
  <strong>Group Size:</strong>
  <%= Group.where(:id => @visitor.group_id)[0].group_size %>
</p>

<p>
  <strong>Email:</strong>
  <%= @visitor.email %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @visitor.contact %>
</p>

<p>
  <strong>City:</strong>
  <%= Zipcode.find(@visitor.zip_code).city %>
</p>

<p>
  <strong>State:</strong>
  <%= Zipcode.find(@visitor.zip_code).state %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @visitor.zip_code %>
</p>

<p>
  <strong>Country:</strong>
  <%= @visitor.country.name %>
</p>

<% @n_questions.each do |ques| %>
    <p>
      <strong><%= ques.question %></strong>
      <% @r = Survey.where(:group_id => @visitor.group_id).where(:question_id => ques.id)%>
      <%= (@r.empty? == true)? "Not Answered" : ((ques.typ == 'choice')? Answer.find(@r[0].answer).answer : @r[0].answer) %>
    </p>
<% end %>

app/views/visitors/edit.html.erb
<!--<h1>Editing Visitor</h1>-->
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Editing Visitor</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>

<%= render 'form' %>

<!--<!= link_to 'Show', @visitor %> |-->
<%= link_to 'Back', visitors_path, class: "btn btn-primary" %>

app/views/visitors/index.csv.erb
<%- headers = ['Last Name', 'First Name'] -%>
<%= CSV.generate_line(headers,:col_sep => ?\t) %>
<%- @visitors = Visitor.where(:created_at => @start_date..@end_date).where(:zip_code => @zipcodes) -%>
<%- @visitors.each do |visitor| -%>
<%= CSV.generate_line([visitor.last_name, visitor.first_name],:col_sep => ?\t) -%>
<%- end -%>

app/views/visitors/new.html.erb
<%= form_for(@visitor) do |f| %>
  <br />
  <br />
  <br />
  <br />

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  
  <div class="field">
    <%= f.label :zip_code %>
    <%= f.text_field :zip_code %>
  </div>

  <div class="field">
    <%= f.label :group_id %>
    <%= f.number_field :group_id %>
  </div>

  <div class="field">
    <%= f.label :country_id %>
    <%= f.number_field :country_id %>
  </div>


  <div class="field">
    <%= f.label :contact%>
    <%= f.radio_button :contact, 0, label: "no", checked: true, inline: true%>
    <%= f.label :contact_no, "no" %> 
    <%= f.radio_button :contact, 1, label: "yes"%>
    <%= f.label :contact_yes, "yes" %>     
   </div> 

  <div class="actions">
    <%= f.submit "submit"%>
  </div>
<% end %>

<!-- </body>
</html> -->

app/views/visitors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Last name:</strong>
  <%= @visitor.last_name %>
</p>

<p>
  <strong>First name:</strong>
  <%= @visitor.first_name %>
</p>

<p>
  <strong>Group:</strong>
  <%= @visitor.group_id %>
</p>

<p>
  <strong>Email:</strong>
  <%= @visitor.email %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @visitor.contact %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @visitor.zip_code %>
</p>

<p>
  <strong>Country:</strong>
  <%= @visitor.country_id %>
</p>

<%= link_to 'Edit', edit_visitor_path(@visitor) %> |
<%= link_to 'Back', visitors_path %>