config/routes.rb
Rails.application.routes.draw do

  # Routes for groups (we want only to create new groups)
  resources :groups, only: [:create, :new]

  # Routes for visitors (we want all CRUD operations)
  resources :visitors

  # Routes for questions (we want CRUD)
  resources :questions

  # Routes for surveys (we want only to create new surveys)
  resources :surveys, only: [:create, :new]

  # Routes for administrators
  resources :admins, only: [:create, :edit, :update, :new]

  # Home page
  root 'groups#new'

  # Administrator section
  get 'admin' => 'visitors_statistics#show'
  get 'administrator' => 'visitors_statistics#show'

  # Visitor singin page
  get 'signin' => 'groups#new', as: 'sign_in'

  # Visitors statistics page
  get 'visitors_statistics/show', as: 'visitors_statistics'

  # Visitors charts page
  get 'charts' => 'visitors_statistics#charts'

  # Visitors flot charts page
  get 'chartkick_charts' => 'visitors_statistics#chartkick_charts'

  # City autocomplete
  get 'zipcodes/city' => 'zipcodes#city'

  # Filtering area
  get 'filter_area'  => 'visitors#filter_area'

  # Routes for administrator login system
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  # Routes for adding a new administrator
  get 'signup'  => 'admins#new'

  # Visitor singin page
  get 'team' => 'groups#team', as: 'team'

  # Password reset
  resources :password_resets, only: [:create, :edit, :update]

  resource :visitors_statistics do
    post 'visitors_in_date'
  end
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :group
  belongs_to :question
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:group_id, :question_id, :answer)
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<%= form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :person_id %><br>
    <%= f.number_field :person_id %>
  </div>
  <div class="field">
    <%= f.label :question_id %><br>
    <%= f.number_field :question_id %>
  </div>
  <div class="field">
    <%= f.label :answer %><br>
    <%= f.text_field :answer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Surveys</h1>

<table>
  <thead>
    <tr>
      <th>Person</th>
      <th>Question</th>
      <th>Answer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= survey.person_id %></td>
        <td><%= survey.question_id %></td>
        <td><%= survey.answer %></td>
        <td><%= link_to 'Show', survey %></td>
        <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
        <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survey', new_survey_path %>

app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Person:</strong>
  <%= @survey.person_id %>
</p>

<p>
  <strong>Question:</strong>
  <%= @survey.question_id %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @survey.answer %>
</p>

<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>